### PR TITLE
Document disabling audio

### PR DESCRIPTION
**Pull request by raboof**
I guess better would be to catch this error and continue without audio in that
case, but not sure how/where to fix that ;)

### CODE REVIEW

**Comment by bsansouci** [comment]
Thanks for this! I didn't know this trick. Do you know if you have an audio device available? It seems like SDL should handle a lot of linux platforms.

**Comment by raboof** [comment]
I do, but for some reason it does not work - it seems SDL was compiled without alsa and/or pulseaudio support, which might be a Debian issue, but I haven't dug into it further.

**Comment by bsansouci** [comment]
https://github.com/bsansouci/SDL-mirror/blob/db0756eec3c5979b8291d739ebac9e8747ccbac2/postinstall.js#L74 this is the configure command we use. Do it look good to you?

**Comment by raboof** [comment]
I don't really have a clue.. http://forums.libsdl.org/viewtopic.php?p=12735 suggests perhaps it needs an explicit `--enable-alsa`?

**Pull request merged**
